# Generate enough data that marginals look Gaussian.
n <- 10000

# Assume that men's heights are normal: N(69.1, 2.9)
# Assume that women's heights are normal: N(63.7, 2.7)
# For now, assume that men and women are each exactly 50% of the population.
heights.weights <- rbind(data.frame(Gender = rep('Male', n / 2),
                                    Height = rnorm(n / 2, 69.1, 2.9)),
                         data.frame(Gender = rep('Female', n / 2),
                                    Height = rnorm(n / 2, 63.7, 2.7)))

# Assume that weights, given heights, are generated by the following linear function.
# This was derived using NHANES data.
#Coefficients:
# (Intercept)  heightInches  
#    -223.904         5.955
heights.weights <- transform(heights.weights, Weight = -223.904 + 5.955 * Height)

# These weights are too high for women. Let's drop 20 pounds.
heights.weights <- transform(heights.weights, Weight = Weight + ifelse(Gender == 'Female', -20, 0))

# Add some Gaussian noise.
heights.weights <- transform(heights.weights, Weight = Weight + rnorm(nrow(heights.weights), 0, 10))

# Save to CSV
write.csv(heights.weights, file = '01_heights_weights_genders.csv', row.names = FALSE)
